### ISSUE TITLE
Median absolute deviation computation

### ISSUE THREAD

**Issue by ghost** [NimSed/astro-machines#1]
Hi, very interesting work!
I think in the paper, the median absolute deviation is used to compute the score of informativeness. But, in the code pandas.mad() is used and it returns the mean absolute deviation. Could you please check? sorry, if I am wrong.

**Comment by NimSed** [comment]
Hi utthisht. 
Thank you very much for your feedback. You are right. However, and fortunately, mean and median give similar results in our case. We now updated the code, leaving it as an option for the user.
Note also that the search for mutual information in the next step, is run across all the dimensions, not only the significant ones detected at this step.
